// US states for the campaign geo-targeting dropdown.
export const US_STATES: { id: string; name: string; abbr: string }[] = [
  { id: 'Alabama', name: 'Alabama', abbr: 'AL' },
  { id: 'Alaska', name: 'Alaska', abbr: 'AK' },
  { id: 'Arizona', name: 'Arizona', abbr: 'AZ' },
  { id: 'Arkansas', name: 'Arkansas', abbr: 'AR' },
  { id: 'California', name: 'California', abbr: 'CA' },
  { id: 'Colorado', name: 'Colorado', abbr: 'CO' },
  { id: 'Connecticut', name: 'Connecticut', abbr: 'CT' },
  { id: 'Delaware', name: 'Delaware', abbr: 'DE' },
  { id: 'District of Columbia', name: 'District of Columbia', abbr: 'DC' },
  { id: 'Florida', name: 'Florida', abbr: 'FL' },
  { id: 'Georgia', name: 'Georgia', abbr: 'GA' },
  { id: 'Hawaii', name: 'Hawaii', abbr: 'HI' },
  { id: 'Idaho', name: 'Idaho', abbr: 'ID' },
  { id: 'Illinois', name: 'Illinois', abbr: 'IL' },
  { id: 'Indiana', name: 'Indiana', abbr: 'IN' },
  { id: 'Iowa', name: 'Iowa', abbr: 'IA' },
  { id: 'Kansas', name: 'Kansas', abbr: 'KS' },
  { id: 'Kentucky', name: 'Kentucky', abbr: 'KY' },
  { id: 'Louisiana', name: 'Louisiana', abbr: 'LA' },
  { id: 'Maine', name: 'Maine', abbr: 'ME' },
  { id: 'Maryland', name: 'Maryland', abbr: 'MD' },
  { id: 'Massachusetts', name: 'Massachusetts', abbr: 'MA' },
  { id: 'Michigan', name: 'Michigan', abbr: 'MI' },
  { id: 'Minnesota', name: 'Minnesota', abbr: 'MN' },
  { id: 'Mississippi', name: 'Mississippi', abbr: 'MS' },
  { id: 'Missouri', name: 'Missouri', abbr: 'MO' },
  { id: 'Montana', name: 'Montana', abbr: 'MT' },
  { id: 'Nebraska', name: 'Nebraska', abbr: 'NE' },
  { id: 'Nevada', name: 'Nevada', abbr: 'NV' },
  { id: 'New Hampshire', name: 'New Hampshire', abbr: 'NH' },
  { id: 'New Jersey', name: 'New Jersey', abbr: 'NJ' },
  { id: 'New Mexico', name: 'New Mexico', abbr: 'NM' },
  { id: 'New York', name: 'New York', abbr: 'NY' },
  { id: 'North Carolina', name: 'North Carolina', abbr: 'NC' },
  { id: 'North Dakota', name: 'North Dakota', abbr: 'ND' },
  { id: 'Ohio', name: 'Ohio', abbr: 'OH' },
  { id: 'Oklahoma', name: 'Oklahoma', abbr: 'OK' },
  { id: 'Oregon', name: 'Oregon', abbr: 'OR' },
  { id: 'Pennsylvania', name: 'Pennsylvania', abbr: 'PA' },
  { id: 'Rhode Island', name: 'Rhode Island', abbr: 'RI' },
  { id: 'South Carolina', name: 'South Carolina', abbr: 'SC' },
  { id: 'South Dakota', name: 'South Dakota', abbr: 'SD' },
  { id: 'Tennessee', name: 'Tennessee', abbr: 'TN' },
  { id: 'Texas', name: 'Texas', abbr: 'TX' },
  { id: 'Utah', name: 'Utah', abbr: 'UT' },
  { id: 'Vermont', name: 'Vermont', abbr: 'VT' },
  { id: 'Virginia', name: 'Virginia', abbr: 'VA' },
  { id: 'Washington', name: 'Washington', abbr: 'WA' },
  { id: 'West Virginia', name: 'West Virginia', abbr: 'WV' },
  { id: 'Wisconsin', name: 'Wisconsin', abbr: 'WI' },
  { id: 'Wyoming', name: 'Wyoming', abbr: 'WY' },
];

export function getStateAbbr(stateName: string): string {
  return US_STATES.find((s) => s.name === stateName)?.abbr || '';
}
